default_install_hook_types:
    - pre-commit
    - pre-push

default_language_version:
    python: python3.10

exclude: migrations

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        stages: [pre-commit]
    -   id: end-of-file-fixer
        stages: [pre-commit]

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
    -   id: python-safety-dependencies-check
        files: pyproject.toml
        stages: [pre-push]

-   repo: https://github.com/iamthefij/docker-pre-commit
    rev: v3.0.1
    hooks:
    -   id: docker-compose-check
        stages: [pre-commit]

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
        stages: [pre-commit]

-   repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
    -   id: check-poetry
        stages: [pre-commit]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]
        stages: [pre-commit]
    -   id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
        stages: [pre-commit]
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        stages: [pre-commit]
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        stages: [pre-commit]
