"""set item price and inventory name to not nullable and fix the max size of every String

Revision ID: fa9f52c0b269
Revises: 6ff916069f29
Create Date: 2024-05-10 11:40:02.654387

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa9f52c0b269"
down_revision: Union[str, None] = "6ff916069f29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("inventory", "name", type_=sa.VARCHAR(250), nullable=False)
    op.alter_column("item", "price", existing_type=sa.REAL(), nullable=False)
    op.alter_column("item", "name", type_=sa.VARCHAR(250))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("item", "name", type_=sa.VARCHAR())
    op.alter_column("item", "price", existing_type=sa.REAL(), nullable=True)
    op.alter_column("inventory", "name", type_=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
